### PR TITLE
misc: remove needs triage label from new bug issues

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR removes the `needs triage` label from the bug issue template. This is causing some confusion with contributors waiting for the needs triage label to be removed in order to pick up an issue, even when the issue doesn’t need it

This label can be added manually when the bug has been evaluated and requires the `need triage` label

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
We do need triage though. The label is meant for either the maintainers or triage team to know which issues need a comment.

I'd prefer a discussion before a PR to ensure we are taking contributions from folks who have context.

**Comment by OgDev-01** [comment]
A lot of folks have reached out asking me to take off `needs triage` label in order for them to work on an issue, and the truth is that most of the bug issues don’t need triaging. IMO we can add the needs triage label to bugs that needs triage manually as opposed to automatically adding it when a bug issue is created. This label is causing some confusions  with new contributors.

**Comment by bdougie** [comment]
> A lot of folks have reached out asking me to take off `needs triage` label in order for them to work on an issue, and the truth is that most of the bug issues don’t need triaging. IMO we can add the needs triage label to bugs that needs triage manually as opposed to automatically adding it when a bug issue is created. This label is causing some confusions  with new contributors.

Sounds like we need more triagers then. I still by the quality of contribution is too low and any opensauced orgs members can remove the label.

We can solve this with education.

**Comment by jpmcb** [comment]
I agree with Brian, we should always try to have a conversation with outside contributors before a change is executed but I can also empathize with people showing up to make small, obvious changes. It can be confusing for them to understand our process if we don't clearly lay out our expectations. We should look at writing a doc or something for users to read to get up to speed on our labeling and triaging practices.

For example, in the past, I've written documents like this to clearly lay this out: https://github.com/spf13/cobra/issues/1603

**Pull request closed without merging**
