### PR TITLE
Create LICENSE

### LINKED ISSUE #50: Bug: open-sauced repo without a open source license
### Describe the bug

There's no open source license, so I really feel like I can't use what's available here.

### Steps to reproduce

1. Go to repository;
2. See that there's no open source license;
3. Cries because the PR/Issue templates are beautiful but you can't use them.

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Additional context (Is this in dev or production?)

Production 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by ArielMAJ**
## Description

This PR adds the best open source license.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [X] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #50

## Mobile & Desktop Screenshots/Recordings

Not necessary.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
Hi @ArielMAJ - thanks for this: the `.github` repository in an organization isn't really meant for general consumption or use by anyone except for those within the org. It denotes the metadata for issue templates, defines the org's code of conduct, etc.

But you're right, it'd be good to add a license since the files for this are open source but I'm unsure if MIT is the right license. We've used Apache 2 in the past given there's some OpenSauced branding.

Blocking until we can talk with the rest of the team on this.

**Comment by ArielMAJ** [comment]
> Hi @ArielMAJ - thanks for this: the `.github` repository in an organization isn't really meant for general consumption or use by anyone except for those within the org. It denotes the metadata for issue templates, defines the org's code of conduct, etc.
> 
> But you're right, it'd be good to add a license since the files for this are open source but I'm unsure if MIT is the right license. We've used Apache 2 in the past given there's some OpenSauced branding.
> 
> Blocking until we can talk with the rest of the team on this.

Tyvm for considering it. I found this repository on a post when researching PR and issue templates for my own projects. I'd like to use them, but I feel like I'm not allowed because of the absence of an open source license.

**Comment by jpmcb** [comment]
cc @bdougie - what license do you think makes sense for this repo?

**Comment by bdougie** [comment]
MIT is fine here

**Review by jpmcb — APPROVED** [review]

**Comment by jpmcb** [comment]
Thanks for starting the conversation @ArielMAJ !! Merged!

**Pull request merged**
