### PR TITLE
feat: adding links to github contributing file

### PR DESCRIPTION
**Pull request by Lymah123**
## This PR makes changes to .github contributing file.
- This is the submission for the issue #44 

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by Lymah123** [comment]
You can review PR @CBID2. I will be waiting for the feedback.

**Review by CBID2 — COMMENTED** [review]
It looks okay so far. @bdougie, what do you think?

**Comment by bdougie** [comment]
I struggle to see the value for adding these links, especially gitpod. 

This opens the door for other in-browser editors to also get added. 

As written it seems like we are selling codespaces and gitpod. Showing is better telling. A better approach a one click link to open the editor but that already exist and it is when you type   .   While in the root of the project.

**Comment by CBID2** [comment]
> I struggle to see the value for adding these links, especially gitpod. 
> 
> This opens the door for other in-browser editors to also get added. 
> 
> As written it seems like we are selling codespaces and gitpod. Showing is better telling. A better approach a one click link to open the editor but that already exist and it is when you type   .   While in the root of the project.

Hi @bdougie. I was thinking back to my earlier experiences in open source, how errors would occur when I tried to setup projects locally in spite of following the contributing guide's directions. So, I pictured a beginner being in this situation, and found that virtual IDEs like Gitpod would be really helpful in getting these individuals ready to contribute. Also, you did recommend adding it to the .github repository.

**Comment by Lymah123** [comment]
> > I struggle to see the value for adding these links, especially gitpod.
> > This opens the door for other in-browser editors to also get added.
> > As written it seems like we are selling codespaces and gitpod. Showing is better telling. A better approach a one click link to open the editor but that already exist and it is when you type   .   While in the root of the project.
> 
> Hi @bdougie. I was thinking back to my earlier experiences in open source, how errors would occur when I tried to setup projects locally in spite of following the contributing guide's directions. So, I pictured a beginner being in this situation, and found that virtual IDEs like Gitpod would be really helpful in getting these individuals ready to contribute. Also, you did recommend [adding it to the .github repository](https://github.com/open-sauced/landing-page/issues/174#issuecomment-1754556187)


Hi @CBID2 and @bdougie, I guess @bdougie  wants us to focus on practical instructions rather than just providing links. Which  I was thinking a step-by-step guide approach aligns with his suggestion. Let me know if I am wrong.

**Pull request closed without merging**
